### PR TITLE
fix(conneciton-pool): fix wrong has_broken condition

### LINKED ISSUE #249: USE statement
attempting something like ``conn.query("USE chubber")?;`` doesn't work for future queries (``Server(CDRSError { error_code: 8704, message: CString { string: "No keyspace has been specified. USE a keyspace, or explicitly specify keyspace.tablename" }, additional_info: Invalid(SimpleError) })`` when trying ``conn.query("SELECT * FROM table;")?;``) and having to write ``keyspace.table`` for every operation gets repetitive.

i notice that there are no docs (or functions like connect_keyspace), so are you already aware of this?

### PR DESCRIPTION
**Pull request by AlexPikalov**
Fixes #249

### CODE REVIEW

File: src/cluster/tcp_connection_pool.rs [hunk 1]
```diff
@@ -122,13 +122,11 @@ pub fn startup<'b, T: CDRSTransport + 'static, A: Authenticator + 'static + Size
...
 
     let auth_token_bytes = session_authenticator.get_auth_token().into_cbytes();
-    try!(
-      transport.borrow_mut().write(
-        Frame::new_req_auth_response(auth_token_bytes)
-          .into_cbytes()
-          .as_slice()
-      )
-    );
+    try!(transport.borrow_mut().write(
```
Comment (AlexPikalov) [inline src/cluster/tcp_connection_pool.rs]: Format change
